version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # RabbitMQ broker
      - "15672:15672"    # RabbitMQ UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  userservice:
    build:
      context: ./UserService
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq

  productservice:
    build:
      context: ./ProductService
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq

  orderservice:
    build:
      context: ./OrderService
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq

  paymentservice:
    build:
      context: ./PaymentService
    ports:
      - "5003:80"
    depends_on:
      - rabbitmq
  apigateway:
    build:
      context: ./ApiGateway
    ports:
      - "8080:80"
    depends_on:
      - userservice
      - productservice
      - orderservice
      - paymentservice