@products_services_HostAddress = http://localhost:5231

GET {{products_services_HostAddress}}/products/
Accept: application/json

###

GET {{products_services_HostAddress}}/products/1
Accept: application/json

###
